name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GDB
      run: sudo apt-get update && sudo apt-get install -y gdb

    - name: Run Tests with GDB on Failure
      run: |
        set -e  # Stop on first failure
        cd tests
        ./unittest.sh || (echo "Test failed, running GDB..." && gdb -batch -ex "run" -ex "bt" --args ./unittest.sh)
        cd ../examples
        ./cpptest.sh || (echo "Test failed, running GDB..." && gdb -batch -ex "run" -ex "bt" --args ./cpptest.sh)
        git diff --exit-code

  build-meson:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        meson-version: 1.4.1
      continue-on-error: false

    - name: Print Meson Test Log on Failure
      if: failure()
      run: cat /home/runner/work/inih/inih/build/meson-logs/testlog.txt
